
import React, { useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/components/ui/collapsible';
import { useToast } from '@/hooks/use-toast';
import { Plus, Package, ChevronDown } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { isInventoryV1Enabled, INVENTORY_DEFAULTS } from '@/utils/featureFlags';
import { createInitialStock } from '@/services/inventoryV1Service';
import { useBranches } from '@/hooks/useBranches';

interface AddProductDialogProps {
  onProductAdded: () => void;
}

export const AddProductDialog: React.FC<AddProductDialogProps> = ({ onProductAdded }) => {
  const [open, setOpen] = useState(false);
  const [loading, setLoading] = useState(false);
  const [inventorySectionOpen, setInventorySectionOpen] = useState(false);
  const [formData, setFormData] = useState({
    name: '',
    description: '',
    price: '',
    hasExpiry: false,
    defaultExpiryDays: '',
    // Inventory V1 fields
    sku: '',
    uom: 'pcs',
    initialStock: '0',
    reorderPoint: '30',
    leadTimeDays: '2',
    shelfLifeDays: '',
    selectedBranch: '',
  });
  const { toast } = useToast();
  const { branches } = useBranches();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    try {
      const productData = {
        name: formData.name,
        description: formData.description,
        price: parseFloat(formData.price),
        active: true,
        has_expiry: formData.hasExpiry,
        default_expiry_days: formData.hasExpiry && formData.defaultExpiryDays 
          ? parseInt(formData.defaultExpiryDays) 
          : null,
        // Simple Inventory V1 fields (only if feature is enabled)
        ...(isInventoryV1Enabled() && {
          sku: formData.sku || null, // Will be auto-generated by trigger if empty
          uom: formData.uom || INVENTORY_DEFAULTS.UOM,
          reorder_point: formData.reorderPoint ? parseInt(formData.reorderPoint) : INVENTORY_DEFAULTS.REORDER_POINT,
          lead_time_days: formData.leadTimeDays ? parseInt(formData.leadTimeDays) : INVENTORY_DEFAULTS.LEAD_TIME_DAYS,
          shelf_life_days: formData.hasExpiry && formData.shelfLifeDays ? parseInt(formData.shelfLifeDays) : null,
        }),
      };

      const { data: product, error } = await supabase
        .from('products')
        .insert(productData)
        .select()
        .single();

      if (error) {
        throw error;
      }

      // Create initial stock if specified and inventory V1 is enabled
      if (isInventoryV1Enabled() && formData.initialStock && 
          parseInt(formData.initialStock) > 0 && formData.selectedBranch) {
        await createInitialStock(
          product.id, 
          formData.selectedBranch, 
          parseInt(formData.initialStock)
        );
      }

      toast({
        title: "Berhasil",
        description: `Produk berhasil ditambahkan${formData.hasExpiry ? ' dengan monitoring kadaluarsa' : ''}${
          parseInt(formData.initialStock || '0') > 0 ? ` dengan stok awal ${formData.initialStock}` : ''
        }`,
      });

      setFormData({ 
        name: '', 
        description: '', 
        price: '', 
        hasExpiry: false, 
        defaultExpiryDays: '',
        sku: '',
        uom: 'pcs',
        initialStock: '0',
        reorderPoint: '30',
        leadTimeDays: '2',
        shelfLifeDays: '',
        selectedBranch: '',
      });
      setOpen(false);
      onProductAdded();
    } catch (error: any) {
      console.error('Error adding product:', error);
      toast({
        variant: "destructive",
        title: "Error",
        description: `Gagal menambahkan produk: ${error.message}`,
      });
    } finally {
      setLoading(false);
    }
  };

  const handleInputChange = (field: keyof typeof formData, value: string | boolean) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button>
          <Plus className="mr-2 h-4 w-4" />
          Tambah Produk
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>Tambah Produk Baru</DialogTitle>
        </DialogHeader>
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="name">Nama Produk</Label>
            <Input
              id="name"
              value={formData.name}
              onChange={(e) => handleInputChange('name', e.target.value)}
              placeholder="Masukkan nama produk"
              required
            />
          </div>
          
          <div className="space-y-2">
            <Label htmlFor="description">Deskripsi</Label>
            <Textarea
              id="description"
              value={formData.description}
              onChange={(e) => handleInputChange('description', e.target.value)}
              placeholder="Masukkan deskripsi produk"
              rows={3}
            />
          </div>
          
          <div className="space-y-2">
            <Label htmlFor="price">Harga</Label>
            <Input
              id="price"
              type="number"
              value={formData.price}
              onChange={(e) => handleInputChange('price', e.target.value)}
              placeholder="Masukkan harga produk"
              min="0"
              step="100"
              required
            />
          </div>

          <div className="space-y-3">
            <div className="flex items-center space-x-2">
              <Checkbox
                id="hasExpiry"
                checked={formData.hasExpiry}
                onCheckedChange={(checked) => handleInputChange('hasExpiry', checked as boolean)}
              />
              <Label htmlFor="hasExpiry" className="text-sm font-medium">
                Produk ini memiliki tanggal kadaluarsa
              </Label>
            </div>
            
            {formData.hasExpiry && (
              <div className="space-y-2 pl-6">
                <Label htmlFor="defaultExpiryDays">Masa kadaluarsa (hari)</Label>
                <Input
                  id="defaultExpiryDays"
                  type="number"
                  value={formData.defaultExpiryDays}
                  onChange={(e) => handleInputChange('defaultExpiryDays', e.target.value)}
                  placeholder="Contoh: 7 untuk seminggu"
                  min="1"
                  max="365"
                  required={formData.hasExpiry}
                />
                <p className="text-xs text-muted-foreground">
                  Produk akan kadaluarsa setelah {formData.defaultExpiryDays || 'X'} hari dari tanggal produksi
                </p>
              </div>
            )}
          </div>

          {/* Simple Inventory V1 Section */}
          {isInventoryV1Enabled() && (
            <Collapsible open={inventorySectionOpen} onOpenChange={setInventorySectionOpen}>
              <CollapsibleTrigger asChild>
                <Button variant="ghost" className="w-full justify-between p-0 font-medium">
                  <div className="flex items-center space-x-2">
                    <Package className="h-4 w-4" />
                    <span>Inventori (Ringkas)</span>
                  </div>
                  <ChevronDown className={`h-4 w-4 transition-transform ${inventorySectionOpen ? 'rotate-180' : ''}`} />
                </Button>
              </CollapsibleTrigger>
              <CollapsibleContent className="space-y-4 pt-4">
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="sku">SKU</Label>
                    <Input
                      id="sku"
                      value={formData.sku}
                      onChange={(e) => handleInputChange('sku', e.target.value)}
                      placeholder="Auto-generate jika kosong"
                    />
                    <p className="text-xs text-muted-foreground">
                      Akan dibuat otomatis jika kosong
                    </p>
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="uom">Satuan (UoM)</Label>
                    <Select value={formData.uom} onValueChange={(value) => handleInputChange('uom', value)}>
                      <SelectTrigger>
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="pcs">Pcs</SelectItem>
                        <SelectItem value="box">Box</SelectItem>
                        <SelectItem value="pak">Pak</SelectItem>
                        <SelectItem value="kg">Kg</SelectItem>
                        <SelectItem value="ltr">Liter</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="initialStock">Stok Awal</Label>
                    <Input
                      id="initialStock"
                      type="number"
                      value={formData.initialStock}
                      onChange={(e) => handleInputChange('initialStock', e.target.value)}
                      placeholder="0"
                      min="0"
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="selectedBranch">Cabang/Lokasi</Label>
                    <Select 
                      value={formData.selectedBranch} 
                      onValueChange={(value) => handleInputChange('selectedBranch', value)}
                      disabled={!formData.initialStock || parseInt(formData.initialStock) === 0}
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="Pilih cabang" />
                      </SelectTrigger>
                      <SelectContent>
                        {branches?.map((branch) => (
                          <SelectItem key={branch.id} value={branch.id}>
                            {branch.name}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="reorderPoint">Reorder Point (ROP)</Label>
                    <Input
                      id="reorderPoint"
                      type="number"
                      value={formData.reorderPoint}
                      onChange={(e) => handleInputChange('reorderPoint', e.target.value)}
                      placeholder="30"
                      min="0"
                    />
                    <p className="text-xs text-muted-foreground">
                      Batas stok menipis
                    </p>
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="leadTimeDays">Lead Time (hari)</Label>
                    <Input
                      id="leadTimeDays"
                      type="number"
                      value={formData.leadTimeDays}
                      onChange={(e) => handleInputChange('leadTimeDays', e.target.value)}
                      placeholder="2"
                      min="1"
                    />
                    <p className="text-xs text-muted-foreground">
                      Estimasi hari restok
                    </p>
                  </div>
                </div>

                {formData.hasExpiry && (
                  <div className="space-y-2">
                    <Label htmlFor="shelfLifeDays">Shelf Life (hari)</Label>
                    <Input
                      id="shelfLifeDays"
                      type="number"
                      value={formData.shelfLifeDays}
                      onChange={(e) => handleInputChange('shelfLifeDays', e.target.value)}
                      placeholder="3"
                      min="1"
                    />
                    <p className="text-xs text-muted-foreground">
                      Umur simpan untuk peringatan kadaluarsa sederhana
                    </p>
                  </div>
                )}
              </CollapsibleContent>
            </Collapsible>
          )}
          
          <div className="flex justify-end space-x-2">
            <Button
              type="button"
              variant="outline"
              onClick={() => setOpen(false)}
              disabled={loading}
            >
              Batal
            </Button>
            <Button type="submit" disabled={loading}>
              {loading ? 'Menyimpan...' : 'Simpan'}
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
};
