-- Add category column to products table
ALTER TABLE public.products 
ADD COLUMN IF NOT EXISTS category text DEFAULT 'produk_utama';

-- Create index for faster category filtering
CREATE INDEX IF NOT EXISTS idx_products_category ON public.products(category);

-- Insert all 214 products from the Excel file
INSERT INTO public.products (name, price, category, has_expiry, product_type, active, description) VALUES
-- PRODUK UTAMA
('2 Rasa', 4000, 'produk_utama', false, 'regular', true, NULL),
('3 Rasa', 6000, 'produk_utama', false, 'regular', true, NULL),
('Bolu Ikan Kecil', 4500, 'produk_utama', false, 'regular', true, NULL),
('Bolu Ikan Besar', 6000, 'produk_utama', false, 'regular', true, NULL),
('Bolu Jadul', 26000, 'produk_utama', false, 'regular', true, NULL),
('Bolu Kasur', 36000, 'produk_utama', false, 'regular', true, NULL),
('Bolu Pandan (Ck.Coklat)', 36000, 'produk_utama', false, 'regular', true, NULL),
('Bolu Zebra', 40000, 'produk_utama', false, 'regular', true, NULL),
('Bolu Gulung Keju', 26000, 'produk_utama', false, 'regular', true, NULL),
('Bolu Gulung Susu', 26000, 'produk_utama', false, 'regular', true, NULL),
('Brownies', 32000, 'produk_utama', false, 'regular', true, NULL),
('Brownies Cup', 4000, 'produk_utama', false, 'regular', true, NULL),
('Burger', 5000, 'produk_utama', false, 'regular', true, NULL),
('Cheese Stick', 4000, 'produk_utama', false, 'regular', true, NULL),
('Choco Cheese Ball', 4500, 'produk_utama', false, 'regular', true, NULL),
('Chocolatos', 4500, 'produk_utama', false, 'regular', true, NULL),
('Choco Chip', 4500, 'produk_utama', false, 'regular', true, NULL),
('Cinnamon', 5000, 'produk_utama', false, 'regular', true, NULL),
('Coklat Meses', 4500, 'produk_utama', false, 'regular', true, NULL),
('Cream Cheese', 6000, 'produk_utama', false, 'regular', true, NULL),
('Croissant Almond', 6000, 'produk_utama', false, 'regular', true, NULL),
('Croissant Mocca', 5500, 'produk_utama', false, 'regular', true, NULL),
('Croissant Strawberry', 5500, 'produk_utama', false, 'regular', true, NULL),
('Croissant Coklat', 5500, 'produk_utama', false, 'regular', true, NULL),
('Cup Cake Coklat', 4500, 'produk_utama', false, 'regular', true, NULL),
('Cup Cake Mix', 4500, 'produk_utama', false, 'regular', true, NULL),
('Cup Cake Fruit', 5000, 'produk_utama', false, 'regular', true, NULL),
('Donat', 2500, 'produk_utama', false, 'regular', true, NULL),
('Donat Mocca', 3000, 'produk_utama', false, 'regular', true, NULL),
('Donat Mini', 2000, 'produk_utama', false, 'regular', true, NULL),
('Garlic Bread', 3000, 'produk_utama', false, 'regular', true, NULL),
('Hot Dog', 5000, 'produk_utama', false, 'regular', true, NULL),
('Kastangel', 80000, 'produk_utama', false, 'regular', true, NULL),
('Kepang Coklat', 5000, 'produk_utama', false, 'regular', true, NULL),
('Kepang Keju', 5000, 'produk_utama', false, 'regular', true, NULL),
('Keju Manis', 4500, 'produk_utama', false, 'regular', true, NULL),
('Keju Susu', 4500, 'produk_utama', false, 'regular', true, NULL),
('Kue Kering', 80000, 'produk_utama', false, 'regular', true, NULL),
('Lapis Legit', 120000, 'produk_utama', false, 'regular', true, NULL),
('Lemon Bread', 5000, 'produk_utama', false, 'regular', true, NULL),
('Molen Keju', 5000, 'produk_utama', false, 'regular', true, NULL),
('Molen Pisang', 5000, 'produk_utama', false, 'regular', true, NULL),
('Molen Banana Chesee', 6000, 'produk_utama', false, 'regular', true, NULL),
('Nastar', 80000, 'produk_utama', false, 'regular', true, NULL),
('Pie Buah', 7000, 'produk_utama', false, 'regular', true, NULL),
('Pisang Coklat', 4000, 'produk_utama', false, 'regular', true, NULL),
('Pisang Coklat Keju', 5000, 'produk_utama', false, 'regular', true, NULL),
('Pizza', 4000, 'produk_utama', false, 'regular', true, NULL),
('Pizza Mini', 3500, 'produk_utama', false, 'regular', true, NULL),
('Pudding Caramel', 4500, 'produk_utama', false, 'regular', true, NULL),
('Pukis', 12000, 'produk_utama', false, 'regular', true, NULL),
('Putri Salju', 80000, 'produk_utama', false, 'regular', true, NULL),
('Red Velvet', 6000, 'produk_utama', false, 'regular', true, NULL),
('Regal', 4500, 'produk_utama', false, 'regular', true, NULL),
('Risol Mayonaise', 4500, 'produk_utama', false, 'regular', true, NULL),
('Risol Ragout', 4500, 'produk_utama', false, 'regular', true, NULL),
('Roti Air', 3000, 'produk_utama', false, 'regular', true, NULL),
('Roti Bakar', 5000, 'produk_utama', false, 'regular', true, NULL),
('Roti Boy', 6000, 'produk_utama', false, 'regular', true, NULL),
('Roti Buaya', 280000, 'produk_utama', false, 'regular', true, NULL),
('Roti Coklat', 3500, 'produk_utama', false, 'regular', true, NULL),
('Roti Kembar', 5000, 'produk_utama', false, 'regular', true, NULL),
('Roti Kupas Coklat', 36000, 'produk_utama', false, 'regular', true, NULL),
('Roti Kupas Mix', 36000, 'produk_utama', false, 'regular', true, NULL),
('Roti O', 5000, 'produk_utama', false, 'regular', true, NULL),
('Roti Sisir', 26000, 'produk_utama', false, 'regular', true, NULL),
('Roti Sobek Coklat', 26000, 'produk_utama', false, 'regular', true, NULL),
('Roti Sobek Keju', 36000, 'produk_utama', false, 'regular', true, NULL),
('Roti Sobek Strawberry', 30000, 'produk_utama', false, 'regular', true, NULL),
('Roti Tawar Biasa', 18000, 'produk_utama', false, 'regular', true, NULL),
('Roti Tawar Kupas', 17000, 'produk_utama', false, 'regular', true, NULL),
('Roti Tawar Pandan', 22000, 'produk_utama', false, 'regular', true, NULL),
('Roti Tawar Gandum', 22000, 'produk_utama', false, 'regular', true, NULL),
('Roti Tiger', 5000, 'produk_utama', false, 'regular', true, NULL),
('Sari Roti Coklat', 3500, 'produk_utama', false, 'regular', true, NULL),
('Sari Roti Keju', 3500, 'produk_utama', false, 'regular', true, NULL),
('Sari Roti Strawberry', 3500, 'produk_utama', false, 'regular', true, NULL),
('Sari Roti Mix', 3500, 'produk_utama', false, 'regular', true, NULL),
('Sate', 4000, 'produk_utama', false, 'regular', true, NULL),
('Sosis Solo', 4500, 'produk_utama', false, 'regular', true, NULL),
('Sarikaya', 5000, 'produk_utama', false, 'regular', true, NULL),
('Sus Coklat', 4000, 'produk_utama', false, 'regular', true, NULL),
('Sus Durian', 5000, 'produk_utama', false, 'regular', true, NULL),
('Sus Fla', 4000, 'produk_utama', false, 'regular', true, NULL),
('Tart Wortel', 5000, 'produk_utama', false, 'regular', true, NULL),
('Tango', 4500, 'produk_utama', false, 'regular', true, NULL),
('Tawar Potong', 1000, 'produk_utama', false, 'regular', true, NULL),
('Vanilla', 4500, 'produk_utama', false, 'regular', true, NULL),
('Kue Cubit', 10000, 'produk_utama', false, 'regular', true, NULL),
('Martabak Biasa', 6000, 'produk_utama', false, 'regular', true, NULL),
('Kepal Coklat', 4500, 'produk_utama', false, 'regular', true, NULL),
('Bantal', 3500, 'produk_utama', false, 'regular', true, NULL),
('Muffin', 5500, 'produk_utama', false, 'regular', true, NULL),

-- MINUMAN
('Aqua Kecil', 3500, 'minuman', false, 'regular', true, NULL),
('Teh Pucuk', 4000, 'minuman', false, 'regular', true, NULL),
('Fanta', 5500, 'minuman', false, 'regular', true, NULL),
('Sprite', 5500, 'minuman', false, 'regular', true, NULL),
('Pepsi Blue', 5500, 'minuman', false, 'regular', true, NULL),
('Milkuat', 3500, 'minuman', false, 'regular', true, NULL),
('Tebs', 5500, 'minuman', false, 'regular', true, NULL),
('Nutriboost', 5500, 'minuman', false, 'regular', true, NULL),
('Coca Cola', 6000, 'minuman', false, 'regular', true, NULL),
('Fruit Tea', 4500, 'minuman', false, 'regular', true, NULL),
('Ale-Ale Kecil', 2500, 'minuman', false, 'regular', true, NULL),
('Teh Kotak', 3500, 'minuman', false, 'regular', true, NULL),
('Teh Gelas', 2500, 'minuman', false, 'regular', true, NULL),
('Yakult', 3000, 'minuman', false, 'regular', true, NULL),
('Pulpy Orange', 7000, 'minuman', false, 'regular', true, NULL),
('Ultramilk', 5500, 'minuman', false, 'regular', true, NULL),
('You C 1000', 6500, 'minuman', false, 'regular', true, NULL),
('Kopiko 78', 6500, 'minuman', false, 'regular', true, NULL),
('Bear Brand', 8000, 'minuman', false, 'regular', true, NULL),
('Nescafe Kaleng', 7000, 'minuman', false, 'regular', true, NULL),
('Good Day Kaleng', 6500, 'minuman', false, 'regular', true, NULL),
('Aqua Sedang', 5000, 'minuman', false, 'regular', true, NULL),
('Aqua Besar', 7000, 'minuman', false, 'regular', true, NULL),
('Plastik Kresek', 500, 'minuman', false, 'regular', true, NULL),
('Pocari Sweat', 7000, 'minuman', false, 'regular', true, NULL),
('Marimas', 1000, 'minuman', false, 'regular', true, NULL),
('Mizone', 5500, 'minuman', false, 'regular', true, NULL),
('Floridina', 4000, 'minuman', false, 'regular', true, NULL),
('Air Gelas', 1000, 'minuman', false, 'regular', true, NULL),
('Nutri Jelly', 3000, 'minuman', false, 'regular', true, NULL),
('Le Mineral', 3500, 'minuman', false, 'regular', true, NULL),
('Cap Kaki Tiga', 7500, 'minuman', false, 'regular', true, NULL),
('Milo Kaleng', 6500, 'minuman', false, 'regular', true, NULL),
('Kopi Good Day Kotak', 5500, 'minuman', false, 'regular', true, NULL),
('Kratingdaeng', 8000, 'minuman', false, 'regular', true, NULL),
('Sprite Kaleng', 5500, 'minuman', false, 'regular', true, NULL),
('Coca Cola Kaleng', 5500, 'minuman', false, 'regular', true, NULL),

-- TITIPAN
('Sambal Icip Kecil', 7000, 'titipan', false, 'regular', true, NULL),
('Sambal Icip Besar', 12000, 'titipan', false, 'regular', true, NULL),
('Sambal Bu Yayuk', 9000, 'titipan', false, 'regular', true, NULL),
('Aci Kriuk', 4000, 'titipan', false, 'regular', true, NULL),
('Sagon', 10000, 'titipan', false, 'regular', true, NULL),
('Kacang Atom', 9000, 'titipan', false, 'regular', true, NULL),
('Keripik Pisang Coklat', 13000, 'titipan', false, 'regular', true, NULL),
('Keripik Pisang Original', 10000, 'titipan', false, 'regular', true, NULL),
('Kopi Toraja', 5000, 'titipan', false, 'regular', true, NULL),
('Gorengan Pedes', 8500, 'titipan', false, 'regular', true, NULL),
('Kerang', 15000, 'titipan', false, 'regular', true, NULL),
('Sale', 16000, 'titipan', false, 'regular', true, NULL),
('Stik Bawang', 10000, 'titipan', false, 'regular', true, NULL),
('Stik Udang', 15000, 'titipan', false, 'regular', true, NULL),
('Macaroni Pedas', 15000, 'titipan', false, 'regular', true, NULL),
('Pangsit Goreng', 8500, 'titipan', false, 'regular', true, NULL),
('Rempeyek Kacang Kecil', 5000, 'titipan', false, 'regular', true, NULL),
('Rempeyek Kacang Besar', 15000, 'titipan', false, 'regular', true, NULL),
('Kapur Barus', 2500, 'titipan', false, 'regular', true, NULL),
('Onde Ketawa', 5000, 'titipan', false, 'regular', true, NULL),
('Bakso Kering', 10000, 'titipan', false, 'regular', true, NULL),
('Kripik Ceker', 20000, 'titipan', false, 'regular', true, NULL),
('Oleh-Oleh Buah', 15000, 'titipan', false, 'regular', true, NULL),
('Kripik Bonggol Pisang', 13000, 'titipan', false, 'regular', true, NULL),
('Kacang Mete', 20000, 'titipan', false, 'regular', true, NULL),
('Krupuk Pangsit Kecil', 4000, 'titipan', false, 'regular', true, NULL),
('Madu', 15000, 'titipan', false, 'regular', true, NULL),
('Rengginang Terasi', 20000, 'titipan', false, 'regular', true, NULL),
('Rengginang Tawar', 15000, 'titipan', false, 'regular', true, NULL),
('Keripik Kangkung', 12000, 'titipan', false, 'regular', true, NULL),
('Keripik Bayam', 15000, 'titipan', false, 'regular', true, NULL),
('Kacang Telur', 13000, 'titipan', false, 'regular', true, NULL),
('Kacang Bawang', 13000, 'titipan', false, 'regular', true, NULL),
('Keripik Usus', 20000, 'titipan', false, 'regular', true, NULL),
('Keripik Jamur', 10000, 'titipan', false, 'regular', true, NULL),

-- PERALATAN ULANG TAHUN
('Lilin Angka Biasa', 5000, 'peralatan', false, 'regular', true, NULL),
('Lilin Angka Putih', 8000, 'peralatan', false, 'regular', true, NULL),
('Lilin Kembang Api', 20000, 'peralatan', false, 'regular', true, NULL),
('Piring Plastik', 5000, 'peralatan', false, 'regular', true, NULL),
('Piring Kertas', 6000, 'peralatan', false, 'regular', true, NULL),
('Lilin Panjang', 1000, 'peralatan', false, 'regular', true, NULL),
('Sendok Plastik', 1000, 'peralatan', false, 'regular', true, NULL),
('Kertas Nasi', 500, 'peralatan', false, 'regular', true, NULL),
('Topi Ultah', 5000, 'peralatan', false, 'regular', true, NULL),
('Lilin Karakter', 8000, 'peralatan', false, 'regular', true, NULL),
('Tulisan Happy Birthday', 5000, 'peralatan', false, 'regular', true, NULL),
('Terompet Ultah', 4000, 'peralatan', false, 'regular', true, NULL),
('Garpu Plastik', 1000, 'peralatan', false, 'regular', true, NULL),
('Pisau Plastik', 1000, 'peralatan', false, 'regular', true, NULL),
('Balon', 1500, 'peralatan', false, 'regular', true, NULL),
('Lilin Nyala Warna', 5000, 'peralatan', false, 'regular', true, NULL),
('Serbet', 10000, 'peralatan', false, 'regular', true, NULL),
('Gelas Plastik', 500, 'peralatan', false, 'regular', true, NULL),
('Lilin Bunga', 8000, 'peralatan', false, 'regular', true, NULL),

-- TART
('Tart 12 CP', 50000, 'tart', false, 'regular', true, NULL),
('Tart 14 CP', 60000, 'tart', false, 'regular', true, NULL),
('Tart 16 CP', 85000, 'tart', false, 'regular', true, NULL),
('Tart 18 CP', 110000, 'tart', false, 'regular', true, NULL),
('Tart 20 CP', 135000, 'tart', false, 'regular', true, NULL),
('Tart 22 CP', 160000, 'tart', false, 'regular', true, NULL),
('Tart 18 Susun 2', 190000, 'tart', false, 'regular', true, NULL),
('Tart 22 Susun 2', 270000, 'tart', false, 'regular', true, NULL),
('Tart Bento Biasa', 25000, 'tart', false, 'regular', true, NULL),
('Tart Bento Karakter', 30000, 'tart', false, 'regular', true, NULL),
('Tart Potong', 3500, 'tart', false, 'regular', true, NULL),
('Tart Black Forest 12', 80000, 'tart', false, 'regular', true, NULL),
('Tart Black Forest 14', 105000, 'tart', false, 'regular', true, NULL),
('Tart Black Forest 16', 145000, 'tart', false, 'regular', true, NULL),
('Tart Black Forest 18', 185000, 'tart', false, 'regular', true, NULL),
('Tart Black Forest 20', 230000, 'tart', false, 'regular', true, NULL),
('Tart Black Forest 22', 285000, 'tart', false, 'regular', true, NULL),

-- ES KRIM (AICE)
('Es Krim Mochi Kelapa', 2000, 'es_krim', false, 'regular', true, NULL),
('Es Krim Semangka', 2000, 'es_krim', false, 'regular', true, NULL),
('Es Krim Histeria', 3500, 'es_krim', false, 'regular', true, NULL),
('Es Krim Sweet Corn Cup', 3000, 'es_krim', false, 'regular', true, NULL),
('Es Krim Choco Stick', 3500, 'es_krim', false, 'regular', true, NULL),
('Es Krim Mochi', 4000, 'es_krim', false, 'regular', true, NULL),
('Es Krim Cone Chocolate', 3000, 'es_krim', false, 'regular', true, NULL),
('Es Krim Cone Vanila', 3000, 'es_krim', false, 'regular', true, NULL),
('Es Krim Susu Telur', 2000, 'es_krim', false, 'regular', true, NULL),
('Es Krim Durian Cup', 3000, 'es_krim', false, 'regular', true, NULL),
('Es Krim Taro Cup', 3000, 'es_krim', false, 'regular', true, NULL),
('Es Krim Choco Cup', 3000, 'es_krim', false, 'regular', true, NULL),
('Es Krim Vanila Cup', 3000, 'es_krim', false, 'regular', true, NULL),
('Es Krim Strawberry Cup', 3000, 'es_krim', false, 'regular', true, NULL),
('Es Krim Coffee', 3000, 'es_krim', false, 'regular', true, NULL);