// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://crlvnhyqadrbpfjjwogf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNybHZuaHlxYWRyYnBmamp3b2dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNDI4ODYsImV4cCI6MjA2MjYxODg4Nn0.buWdzKs-P_fzK9pu___qQyk0l5ijjsFTALA6pPjfrZg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);